// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// twdtw
double twdtw(const NumericMatrix& ts1, const NumericMatrix& ts2, const DateVector& ts1_date, const DateVector& ts2_date, double alpha, double beta);
RcppExport SEXP _twdtwr_twdtw(SEXP ts1SEXP, SEXP ts2SEXP, SEXP ts1_dateSEXP, SEXP ts2_dateSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts1(ts1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ts2(ts2SEXP);
    Rcpp::traits::input_parameter< const DateVector& >::type ts1_date(ts1_dateSEXP);
    Rcpp::traits::input_parameter< const DateVector& >::type ts2_date(ts2_dateSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(twdtw(ts1, ts2, ts1_date, ts2_date, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_twdtwr_twdtw", (DL_FUNC) &_twdtwr_twdtw, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_twdtwr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
