# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twdtw <- function(ts1, ts2, ts1_date, ts2_date, alpha, beta) {
    .Call(`_twdtwr_twdtw`, ts1, ts2, ts1_date, ts2_date, alpha, beta)
}

