# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_cycle_length <- function(cycle_length, time_scale) {
    .Call(`_twdtwr_max_cycle_length`, cycle_length, time_scale)
}

twdtw <- function(ts1, ts2, ts1_dates, ts2_dates, cycle_length, time_scale, alpha, beta) {
    .Call(`_twdtwr_twdtw`, ts1, ts2, ts1_dates, ts2_dates, cycle_length, time_scale, alpha, beta)
}

